### ISSUE TITLE
Patch request to bucket/{id} returns 500 error

### ISSUE THREAD

**Issue by stuartphilp** [mozilla-services/cliquet#516] opened 2015-10-28 18:50 UTC
During testing for updating on a existing bucket as per:
http://kinto.readthedocs.org/en/latest/api/buckets.html#updating-an-existing-bucket

I created a bucket called "test_bucket" using the bucket create endpoint, then tried updating that bucket using the patch endpoint. This was done through a python script, but the equivalent curl command is:

curl --request patch https://kinto.stage.mozaws.net/v1/buckets/test_bucket --user testuser:abc123

which returns:

{"info":"https:\/\/github.com\/mozilla-services\/cliquet\/issues\/","errno":999,"message":"A programmatic error occured, developers have been informed.","code":500,"error":"Internal Server Error"}

cc @tarekziade

**Comment by stuartphilp** [comment] 2015-10-28 19:59
just to note this happens with patch collections as well (and likely other endpoints). it's probably due to having a patch request without any data to modify on the object. a patch request that supplies something to update seems to work fine.

**Comment by leplatrem** [comment] 2015-10-28 20:32
Thanks @stuartphilp for this feedback !

Indeed I believe this one to be a duplicate of #477

**Closed** 2015-10-29 10:19 UTC
Labels: bug
